name: entregatudo
description: "Entregas da EntregaTudo."
publish_to: 'none'

version: 1.1.7+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter  
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.17.0
  geolocator: ^13.0.2
  permission_handler: ^11.0.1
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/Voz.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
